//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDSTP.APIService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDSTP.APIService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barrio;perimetro;area;comuna;calle_sede;altura_sede;tel_sede;lat_sede;long_sede;geojson
        ///RECOLETA;21246.6;6140873.29113344;2;J. E. Uriburu ;1022;4823-1165/72;-34.5966;-58.3992;&quot;{&quot;&quot;type&quot;&quot;:&quot;&quot;MultiPolygon&quot;&quot;,&quot;&quot;coordinates&quot;&quot;:[[[[-58.39521,-34.57219],[-58.39482,-34.57231],[-58.39432,-34.57229],[-58.39432,-34.57229],[-58.39331,-34.57222],[-58.39321,-34.57221],[-58.3928,-34.57224],[-58.39279,-34.57224],[-58.39134,-34.57302],[-58.39123,-34.57309],[-58.38496,-34.57649],[-58.38496,-34.57649],[-58.38472,-34.57648],[-58 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string comunas {
            get {
                return ResourceManager.GetString("comunas", resourceCulture);
            }
        }
    }
}
